BusBoard Part3
ClaireLi1/BusBoard pull request #3
Opened 2024-07-15 10:17 UTC by ClaireLi1

Build a website to display the busboard

2024-07-15 15:29 UTC, davidm-m requested changes
Your code looks good and you've structured it nicely across models, views, and controllers which is excellent.

I've left a couple of comments on things to improve but I'm also interested in how you think your website could be extended. It's a bit bare-bones at the moment: not very interesting to look at, only does one thing, and difficult to read (does the user need to see the stop ID?).
Do you have any ideas for what could be done to improve the site? And how would you approach implementing your ideas?

2024-07-15 15:29 UTC, davidm-m commented on app/controllers/bus_prediction_controller.rb
> +    # Rails.logger.debug "Predictions: #{@results.inspect}"
In general you should avoid committing commented-out code, especially if it was for debugging.

2024-07-15 15:29 UTC, davidm-m commented on app/models/concerns/web_request.rb
> +module WebRequest
The distinction is a bit fuzzy but this strikes me as a helper rather than a concern. A concern adds additional functionality to a class that includes it, whereas helpers are normally static (i.e. completely unconnected from a class) methods that do something useful.
I would rename this `web_request_helper` and put it in the `helpers` folder.

2024-07-17 08:42 UTC, ClaireLi1 commented
Improvements made:
- Handle cases where invalid postcode is entered, errors when fetching from API.
- Handle cases where results/part of results is empty.
- Improve UI design.
- Make the messages more comprehensive and readible.

2024-07-17 14:00 UTC, davidm-m approved these changes
Very nice! It looks good and handles user input much more robustly now.

2024-07-17 14:15 UTC, merged